#ifndef __PARAMETERS_H__
#define __PARAMETERS_H__

#define HASH_TABLE_BUCKETS_SIZE 20
#define ONE_MEGABYTE_IN_BYTES 1000000UL
#define MEMORY_LIMIT (500UL * ONE_MEGABYTE_IN_BYTES)
#define MAX_EVICTIONS_PER_OPERATION 10

#endif
