#ifndef __PARAMETERS_H__
#define __PARAMETERS_H__

#define HASH_TABLE_BUCKETS_SIZE 10000
#define ONE_MEGABYTE_IN_BYTES 1000000UL
#define MEMORY_LIMIT (1000UL * ONE_MEGABYTE_IN_BYTES)
#define MAX_EVICTIONS_PER_OPERATION 50
#define MAX_EVICTION_ATTEMPTS 20

#endif
